[folders]
src = "./src" # Source folder for all python code, cannot overwrite with local config files
dataSources = "./dataSources" # Location of all source related files, cannot overwrite with local config files
logs = "./logs" # Location of all logging files, cannot overwrite with local config files

[overwrites]
storage = "" # Location overwrite for source data including downloading/processing/conversion, leave blank to keep in respective dataSource location, new location will have dataSources folder structure
package = "" # Location overwrite for packaged files to be put in, leave blank to leave in respective dataSource location

[settings]
logToConsole = true
logLevel = "info" # Log levels: debug, info, warning, error, critical
