Files: # Entries should be paths relative to root directory (arga-data)
  Sources: "arga-sources.json" # Location of sources and relevant information for sources
  DwC mapping: "dwcMapping.json" # Mapping from non DwC fields to DwC
  Other mapping: "customMapping.json"  # Additionally mapping to other fields
  Excluded entries: "exclude.json" # Exclude entries by a DwC field, such as taxid

Directories: # Entries should be paths relative to root directory (arga-data)
  Source: "src" # Source folder for all python code
  Data: "data" # Location to store downloaded data from data sources
  Results: "data/results" # Location to store smaller files from processing larger files
  Generated files: "generatedFiles" # Base location of any generated files
  Generated examples: "generatedFiles/examples" # Location to store all example files
  DwC files: "generatedFiles/dwc" # Location to store all output darwin core files
  Logging: "logs" # Location of all logging files
