[folders]
logs = "./logs" # Location of all logging files, cannot overwrite with local config files

[storage]
data = "" # Location overwrite for source data including downloading/processing/conversion, leave blank to keep in respective dataSource location, new location will have dataSources folder structure
package = "" # Location overwrite for packaged files to be put in, leave blank to leave in respective dataSource location

[files]
secrets = "./secrets.toml" # Secrets file for storing sensitive information

[logging]
logToConsole = true
logLevel = "info" # Log levels: debug, info, warning, error, critical
